name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/notification.png
    - assets/images/google.png

  fonts:
    - family: "InterLight"
      fonts:
        - asset: assets/fonts/Inter-Light-slnt=0.ttf
    - family: "InterRegular"
      fonts:
        - asset: assets/fonts/Inter-Regular-slnt=0.ttf
    - family: "InterMedium"
      fonts:
        - asset: assets/fonts/Inter-Medium-slnt=0.ttf
    - family: "InterSemiBold"
      fonts:
        - asset: assets/fonts/Inter-SemiBold-slnt=0.ttf
    - family: "InterBold"
      fonts:
        - asset: assets/fonts/Inter-Bold-slnt=0.ttf

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs