name: todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  string_validator: ^0.1.4
  shared_preferences: ^0.5.12+4
  google_sign_in: ^4.5.6
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  modal_bottom_sheet: ^1.0.0+1
  date_time_picker: ^1.1.0
  animations: ^1.1.2
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  flutter_modular: ^2.0.1
  flutter_screenutil: ^4.0.0-beta1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/empty.png

  fonts:
    - family: "InterLight"
      fonts:
        - asset: assets/fonts/Inter-Light-slnt=0.ttf
    - family: "InterRegular"
      fonts:
        - asset: assets/fonts/Inter-Regular-slnt=0.ttf
    - family: "InterMedium"
      fonts:
        - asset: assets/fonts/Inter-Medium-slnt=0.ttf
    - family: "InterSemiBold"
      fonts:
        - asset: assets/fonts/Inter-SemiBold-slnt=0.ttf
    - family: "InterBold"
      fonts:
        - asset: assets/fonts/Inter-Bold-slnt=0.ttf

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs
